-- Add BPM column to tracks.
ALTER TABLE tracks ADD COLUMN bpm REAL;

-- Clear all cached waveforms: the blob format changes from [f32 × N] (mono RMS)
-- to [f32 × 3 × N] (interleaved low/mid/high RMS per bucket).
-- They will be regenerated by the background analysis queue on next startup.
DELETE FROM waveforms;
